config/routes.rb
Web::Application.routes.draw do
  
  resources :categories
  
  resources :anuncios

  resources :anuncios, :only => [:show] do
    member do
      post :activar
      post :desactivar
    end
  end
  
  resources :users
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "painel" => "users#painel", :as => "painel"

  get "profile" => "users#show", :as => "profile"
  
  get "venda" => "anuncios#venda", :as => "venda"
  get "compra" => "anuncios#compra", :as => "compra"
  get "troca" => "anuncios#troca", :as => "troca"
  
  get "desactivos" => "anuncios#desactivos", :as => "desactivos"

  get "estatisticas" => "anuncios#estatisticas", :as =>"estatisticas"

  

  root :to => "users#new"

  get "pesq" => "anuncios#find_anuncios", :as => "pesq"
  get "dashboard" => "anuncios#dashboard" ,:as => "dashboard"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username,:email, :password, :password_confirmation, :status,:dashboard
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_length_of :password ,:minimum => 5 , :on => :create
  validates_presence_of :password, :on => :create
  validates_presence_of :email , :username
  validates_uniqueness_of :email, :username

  validates :status, :inclusion => { :in => ['R', 'A', 'M'] }
  
  has_many :anuncios

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end



  def self.search(username)
     if username
      where('username LIKE ?',"%#{username}%")
    else
      scoped
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  skip_before_filter :authorize, :except => :show
  
  before_filter :authorize_admin
  

  before_filter :correct_user ,:only => [:edit ,:update ]
  skip_before_filter :authorize_admin , :except => [ :index,:painel ]
   #se nao for admin nao tem autorizacao para entrar
  # GET /users
  # GET /users.json
  def index
    @users = User.search(params[:username])

  end


  def painel

  end

  # GET /users/1
  # GET /users/1.json
  def show
   #@user = User.find(params[:id])
    #verifica se exite algum id no link
    @user = !params[:id].nil? ? User.find(params[:id]) : current_user
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to "/log_in", :notice => "Signed up!"
    else
      render "new"
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @anuncios = Anuncio.find_by_user_id(@user.id)
    @user.anuncios.each{ |anuncio| anuncio.destroy}
    @user.destroy

    respond_to do |format|
      format.html { redirect_to anuncios_url }
      format.json { head :no_content }
    end
  end

 
end

app/helpers/users_helper.rb
module UsersHelper


	def to_s_status(status)

		case status
		when "M"
			a = 'Moderador'
		when "R"
			a = 'Registado'
		when "A"
			a = 'Administrador'
		end

		return a
	end
	
	def to_s_moderador(dashboard)

		case dashboard
		when "N"
			a = 'Normal'
		when "E"
			a = 'Estatisticas'
		end

		return a
	end
end

app/views/users/_anuncios.html.erb
<ul class="thumbnails related_products">
  <% @user.anuncios.each do |anuncio| %>
     <li class="span2">
           <div class="thumbnail">
              <%= link_to (image_tag anuncio.assets.first.image(:small)) , anuncio %>
            <div class="caption">

                      <h5><%= anuncio.nome %></h5></a>  Preço: €<%= anuncio.preco %><br /><br />
                         <h3></h3>
                            <p><%= anuncio.descricao %></p>
                            
                              <p>
                                <b>Nome:</b>
                                <%= anuncio.nome %>
                              </p>

                              <p>
                                <b>Descricao:</b>
                                <%= anuncio.descricao %>
                              </p>
                              <p><%= link_to 'Show ', anuncio %>&nbsp;&nbsp;&nbsp;&nbsp;
                               <% if isModerador? || belongs_toUser?(anuncio.user_id)%>
                                <%= link_to 'Edit', edit_anuncio_path(anuncio) %>
                              <% end %>
            </div>
          </div>
        </li>
  <% end %>
</ul>
   

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <fieldset>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <%= f.label :password %><br />
     <p>
          <%= f.password_field :password,:placeholder => 'Password' %>
        </p>
        <p>
          <%= f.password_field :password_confirmation ,:placeholder => 'Re-Enter Password'%>
        </p>

  <br>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.hidden_field :status,:id =>"btn-input", :value => @user.status %>
  </div>

<div class="input">
   <select name="user[dashboard]"  class="selectpicker"> 
      <option value="">Please select</option> 
      <option value="N" >Normal</option> 
      <option value="E" >Estatisticas</option> 
    </select>
 </div><br >



  <!--se for a pagina for de edicao mostra opcao de mudar status do User-->
  <% if current_page?(edit_user_path) %>

    <div class="btn-group" data-toggle="buttons-radio">
         <button name="status" type="button" class="btn <%= 'active' if @user.status == 'R' %>" value="R" onClick="$('#btn-input').val( $(this).val() );">Normal</button>
         <button name="status" type="button" class="btn <%= 'active' if @user.status == 'M' %>" value="M" onClick="$('#btn-input').val( $(this).val() );">Moderador</button>
         <button name="status" type="button" class="btn <%= 'active' if @user.status == 'A' %>" value="A" onClick="$('#btn-input').val( $(this).val() );">Administrador</button>
      <% end %>
    </div>
    <br><br><br><br>
</fieldset>
  <div class="actions">
     <%= f.submit "Actualizar Utilizador",:class => "btn btn-primary" %>
    
  </div>
 <br>
<% end %>

app/views/users/_users.html.erb
 <table  class="table table-striped sortable1">
  <thead>
    <tr>
      <th data-sort='Username'>Username</th>
      <th data-sort='Email'>Email</th>
      <th data-sort='Status'>Status</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user %></td>
      <td><%= user.email %></td>
      <td><%= user.status %></td>
      <td></td>
      <% if isAdmin? %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <%end %>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>

  <br />

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Lista de Utilizadores</h1>
<br>

<%= form_tag users_path, :method => 'get'  ,:class => 'form-inline', :id=>'users_search' do  %>
   <%= text_field_tag :username, params[:username], :class =>"span5 search-input",:placeholder => "Search by Username...",:autocomplete=>"off" %>

<br><br>
<div id="users">  
  <%= render :partial =>'users' %>
<div>

<%= link_to 'New User', new_user_path,:class => 'btn' %>

<% end %>
</div>
</div>

app/views/users/index.js.erb
$("#users").html("<%= escape_javascript(render :partial => ("users")) %>");

app/views/users/new.html.erb
 <div id="login">
    <h1>Registar-se ou fazer <%= link_to "Login", log_in_path, :method => "get" %> </h1>

    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <fieldset>
         <p>
          <%= f.text_field :username, :placeholder => 'Username',:onBlur=>"if(this.value=='')this.value='Username'",:onFocus=>"if(this.value=='Username')this.value='' "%>
        </p>
        <p>
          <%= f.text_field :email,:placeholder => 'Email',:onBlur=>"if(this.value=='')this.value='Email'",:onFocus=>"if(this.value=='Email')this.value='' "  %>
        </p>
        <p>
          <%= f.password_field :password,:placeholder => 'Password' %>
        </p>
        <p>
          <%= f.password_field :password_confirmation ,:placeholder => 'Re-Enter Password'%>
        </p>
        <p class="button"><%= f.submit %></p>

    </fieldset>
    <% end %>
</div>

app/views/users/painel.html.erb
<div class="row-fluid">
    <div class="block span6">
        <a href="#tablewidget" class="block-heading" data-toggle="collapse">Ultimas Anuncios<span class="label label-warning">+8</span></a>
        <% @ultimos_anuncios = ultimos_anuncios(8) %>
        <div id="tablewidget" class="block-body collapse in">
        
        </div>
        <table class="table table-striped sortable1" >
              <thead>
                <tr>
                  <th data-sort='Nome'>Nome</th>
                  <th>Descricao</th>
                  <th data-sort='Preco'>Preco</th>
                  <th data-sort='Categoria'>Categoria</th>
                  <th data-sort='Tipo'>Tipo</th>
                </tr>
              </thead>

            <% @ultimos_anuncios.each do |anuncio| %>
               <%  id_cat2nome(anuncio.category_id) %>
              <tr>
                <td><%=link_to anuncio.nome , anuncio%></td>
                <td><%= anuncio.descricao %></td>
                <td><%= anuncio.preco unless (anuncio.tipo == "TIPO") %>€</td>
                <td><%= @nome_categoria %></td>
                <td><%= anuncio.tipo %></td>
              </tr>
            <% end %>
            </table>
    </div>
    
    <div class="block span6">
        <a href="#widget1container" class="block-heading" data-toggle="collapse">Estatisticas </a>
        <div id="widget1container" class="block-body collapse in">
           <div id="tablewidget" class="block-body collapse in">
            <%= high_chart("my_id1", get_grafico_anuncio_categoria ) %>
        </div>
      </div>
    </div>

   

   
    
    <div class="block span6">
        <a href="#widget1container1" class="block-heading" data-toggle="collapse">Ranking Utilizadores </a>
        <div id="widget1container1" class="block-body collapse in">
           <div id="tablewidget" class="block-body collapse in">
            <% @lista_users =  ranking_anuncios %>

                 <table class="table table-striped sortable1" >
                      <thead>
                          <tr>
                            <th data-sort='Nome'>Nome</th>
                            <th data-sort='Numero de anuncios'>Nº anuncios</th>
                          </tr>
                      </thead>
                        <% @lista_users.each do |l| %>
                          <tr>
                            <td><%= link_to l.username, "/users/"+l.id.to_s %></td>

                            <td><%= l.n_anuncios %></td>
                          </tr>
                        <% end %>
                 </table>
        </div>
      </div>
    </div>

     <div class="block span6">
        <a href="#widget1container" class="block-heading" data-toggle="collapse">Estatisticas </a>
        <div id="widget1container" class="block-body collapse in">
           <div id="tablewidget" class="block-body collapse in">
            <%= high_chart("my_id", get_grafico_precos_medios_cat ) %>
        </div>
      </div>
    </div>




</div>

app/views/users/show.html.erb
<div id="mainBody">
<div class="container">
	<hr class="soften">
	<h1><%= @user.username %> perfil</h1>
	<hr class="soften"/>	
	<div class="row">
		<div class="span4">
		<h4><strong>Username: </strong> <span><%= @user.username %></span><br><br></h4>
		<p>	 <h2>
              <strong> <b>Email:</b><%= @user.email %></strong> <br /><br />
              </h2>
			 <strong> 
			<% if current_page?("/profile") %>
				 <b>Status:</b> 
				 	<%=	to_s_status(@user.status) %> <br><br>

				 <strong><b>Dashboard:</b>
	 				 <%= to_s_moderador(@user.dashboard) %></strong><br /><br />
			<% end %>
			<%= link_to 'Editar', edit_user_path(@user),:class=>'btn btn-primary' %>
	<br><br>
		</p>		
		</div>
			
		<div class="span4">
		<h4>Info</h4><br>
		 <strong> Numero de anuncios activos: <span class="label label-warning"><%= @user.anuncios.where(:activo => 1).length %></span></strong><br /><br />
			<h5> <strong>Numero de negocios realizados <span class="label label-important"><%= @user.anuncios.where(:activo => 0).length %></strong></span></h5>


		</div>


		<div class="span4">
		<h4>Envia-me um email</h4><br>
		<form class="form-horizontal">
        <fieldset>
          <div class="control-group">
           
              <input type="text" placeholder="name" class="input-xlarge"/>
           
          </div>
		   <div class="control-group">
           
              <input type="text" placeholder="email" class="input-xlarge"/>
           
          </div>
		   <div class="control-group">
           
              <input type="text" placeholder="subject" class="input-xlarge"/>
          
          </div>
          <div class="control-group">
              <textarea rows="3" id="textarea" class="input-xlarge"></textarea>
           
          </div>

            <button class="btn " type="submit">Send Messages</button>

        </fieldset>
      </form>
		</div>
	</div>
</div>
</div>

<%= link_to_function "Ver anuncios", "$('.anuncios_user').slideToggle();",:class =>'btn btn-primary' %><br><br>
	<div class="anuncios_user">
		<%= render 'anuncios', collection: @user.anuncios %>
	</div>
<!-- MainBody End ============================= -->