config/routes.rb
Web::Application.routes.draw do
  
  resources :categories
  
  resources :anuncios

  resources :anuncios, :only => [:show] do
    member do
      post :activar
      post :desactivar
    end
  end
  
  resources :users
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "painel" => "users#painel", :as => "painel"

  get "profile" => "users#show", :as => "profile"
  
  get "venda" => "anuncios#venda", :as => "venda"
  get "compra" => "anuncios#compra", :as => "compra"
  get "troca" => "anuncios#troca", :as => "troca"
  
  get "desactivos" => "anuncios#desactivos", :as => "desactivos"

  get "estatisticas" => "anuncios#estatisticas", :as =>"estatisticas"

  

  root :to => "users#new"

  get "pesq" => "anuncios#find_anuncios", :as => "pesq"
  get "dashboard" => "anuncios#dashboard" ,:as => "dashboard"

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :nome, :id,:cassets_attributes

  validates :nome, :presence => true

  has_many :anuncios
  has_many :cassets, :dependent => :destroy
  accepts_nested_attributes_for :cassets
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_filter :authorize_backend #se nao for authorize_moderador nao tem autorizacao para entrar
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @category = Category.new
    1.times { @category.cassets.build }
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    1.times { @category.cassets.build }
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    1.times { @category.cassets.build }
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    @category.anuncios.each{ |anuncio| anuncio.destroy}

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>

  <div class="newPaperclipFiles">

        <%= f.fields_for :cassets do |asset| %>
        
           <% if asset.object.new_record? %>
                 <%= asset.file_field :image %>
           <% end %>

       <% end %>

  </div>

  <div class="existingPaperclipFiles">
          
       <% f.fields_for :cassets do |asset| %>
          
            <% unless asset.object.new_record? %>
          
                  <div class="thumbnail">
                          <%= link_to( image_tag(asset.object.image.url(:thumb)), asset.object.image.url(:original) ) %>
                          <%= asset.check_box :_delete %>
                  </div>
                  
            <% end %>        
          
       <% end %>
  </div><br >
  <div class="actions">
    <%= f.submit "Adicionar Categoria",:class => "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<table class="table table-striped sortable1" >
  <thead>
    <tr>
      <th data-sort='Nome'>Nome</th>
      <th data-sort='Nº anuncios'>Nº Anuncios</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @categories.each do |category| %>
  <tr>
    <td><%=link_to category.nome, category %></td>
    <td><%= category.anuncios.count %></td>
    <td><%= link_to 'Editar', edit_category_path(category) %></td>
    <td><%= link_to 'Apagar', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= render 'form' %>
<br>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @category.nome %>
</p><br>


 <%= image_tag @category.cassets.first.image(:small) %><br>


<%= link_to 'Edit', edit_category_path(@category),:class=> 'btn btn-primary' %> 
<%= link_to 'Back', categories_path ,:class=> 'btn' %>