config/routes.rb
Web::Application.routes.draw do
  
  resources :categories
  
  resources :anuncios

  resources :anuncios, :only => [:show] do
    member do
      post :activar
      post :desactivar
    end
  end
  
  resources :users
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "painel" => "users#painel", :as => "painel"

  get "profile" => "users#show", :as => "profile"
  
  get "venda" => "anuncios#venda", :as => "venda"
  get "compra" => "anuncios#compra", :as => "compra"
  get "troca" => "anuncios#troca", :as => "troca"
  
  get "desactivos" => "anuncios#desactivos", :as => "desactivos"

  get "estatisticas" => "anuncios#estatisticas", :as =>"estatisticas"

  

  root :to => "users#new"

  get "pesq" => "anuncios#find_anuncios", :as => "pesq"
  get "dashboard" => "anuncios#dashboard" ,:as => "dashboard"

  

end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
  attr_accessible :activo, :dataSubmissao, :descricao, :destaque, :nome, :preco, :tipo, :user_id, :category_id ,:assets_attributes

  validates :user_id, :presence => true
  validates :category_id, :presence => true
  validates :nome,:descricao,:tipo, :presence => true
  validates :assets,:presence => true
  belongs_to :user
  belongs_to :category

  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :assets

  #procura por nome
  def self.search(nome,tipo,category_id)
	   if nome
      where('(nome LIKE ? or descricao LIKE ?) and tipo LIKE ? and activo == 1',"%#{nome}%","%#{nome}%","%#{tipo}%")
     elsif !category_id.nil?
      where('category_id = ? and activo == 1',category_id)
      else
       where('tipo LIKE ? and activo == 1',"%#{tipo}%")
    end
  end

  #devolve anuncios desactivos
  def self.desactivos
    find(:all,:conditions => ['activo == 0'])
  end
  

  #procura avançada
  def self.advanced_search(nome,category_id,tipo,minimum_price,maximum_price)

    anuncios = limit(1000)
    anuncios = anuncios.where('nome LIKE ? or descricao LIKE ?',"%#{nome}%","%#{nome}%") unless nome.nil? || nome.blank?
    anuncios = anuncios.where("preco >= ? ",minimum_price) unless  minimum_price.blank? ||  minimum_price.nil?
    anuncios = anuncios.where("preco < ? ",maximum_price) unless maximum_price.nil? || maximum_price.blank?

    
    if category_id != "Todas as categorias"
          anuncios = anuncios.where("category_id = ?",category_id)
    end


    case tipo
      when "Compra"
        anuncios = anuncios.where("tipo LIKE ?","%Compra%")
      when "Todos os tipos"
        anuncios = anuncios.where("tipo LIKE ?","%%")
      when "Venda"
        anuncios = anuncios.where("tipo LIKE ?","%Venda%")
      when "Troca"
         anuncios = anuncios.where("tipo LIKE ?","%Troca%")
    end


    anuncios

  end



  
end

app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController
  include Paperclip::Glue

  skip_before_filter :authorize, :except => :new
  helper_method :sort_column, :sort_direction,:get_nome_categoria

  #before_filter :authorize_moderador,:only =>[ :edit ]
  before_filter :correct_anuncio , only: [ :edit , :update , :destroy]
  
  # GET /anuncios
  # GET /anuncios.json
  def index
    @anuncios = Anuncio.order(sort_column + " " + sort_direction).paginate(:per_page => 9, :page => params[:page]).search(params[:nome],"",params[:category_id])
    @categories = Category.find( :all , :order => 'nome ')

    
    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.xml  { render :xml => @anuncios }
    end
  end

  # /venda com anuncios de venda
  def venda
    @anuncios = Anuncio.order(sort_column + " " + sort_direction).paginate(:page => params[:page],:per_page => 9).search(params[:nome],"Venda",params[:category_id]) 
    @categories = Category.find( :all , :order => 'nome ')
  end

  # /compra anuncios de compra
  def compra
    @anuncios = Anuncio.order(sort_column + " " + sort_direction).paginate(:page => params[:page],:per_page => 9).search(params[:nome],"Compra",params[:category_id]) 
    @categories = Category.find( :all , :order => 'nome ')
  end

  # anuncios de trocas
  def troca
    @anuncios = Anuncio.order(sort_column + " " + sort_direction).paginate(:page => params[:page],:per_page => 9).search(params[:nome],"Troca",params[:category_id]) 
    @categories = Category.find( :all , :order => 'nome ')
  end

  # /desactivos anuncios que estao desactivos(activo = 0)
  def desactivos
    @anuncios = Anuncio.order(sort_column + " " + sort_direction).paginate(:page => params[:page],:per_page => 9).desactivos
  end

  #  para activar um anuncio
  def activar
    @anuncio = Anuncio.find(params[:id])
    @anuncio.activo = 1
    @anuncio.save

    render :show
  end

  # para desactivar um anuncio
  def desactivar
    @anuncio = Anuncio.find(params[:id])
    @anuncio.activo = 0
    @anuncio.save

    render :show

  end

  # /dashboard
  def dashboard
    @categories = Category.find( :all , :order => 'nome ')

    @destaques1 = Anuncio.find(:all,:conditions =>[ "destaque = ?",true],:limit => 4,:order => "preco asc")
    @destaques2 = Anuncio.find(:all,:conditions =>[ "destaque = ?",true],:limit => 4,:order => "preco desc")

    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /anuncios/1
  # GET /anuncios/1.json
  def show
    @anuncio = Anuncio.find(params[:id])

    category_id = @anuncio.category_id

    #buscar anuncios parecidos mesma catgoria por exemplo
    @anuncios_relacionados = Anuncio.find(:all, :conditions =>[ "category_id = ?",category_id],:limit => 3)

    if !@anuncio.category_id.blank?
       @category_name = Category.find(@anuncio.category_id).nome
    else
        @category_name = "Sem Categoria"
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @anuncio }
    end
  end

  #devolve valores para os graficos das estatisticas
  def estatisticas

      @obj1 = categoria_percent
        
      @obj = avg_price_categoria

      @h = get_grafico(@obj,"bar")

      @h1 = get_grafico(@obj1,"pie")
  end

  # GET /anuncios/new
  # GET /anuncios/new.json
  def new
    @anuncio = Anuncio.new
    @categories = Category.all
    
    3.times { @anuncio.assets.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @anuncio }
    end
  end

  # GET /anuncios/1/edit
  def edit
    @anuncio = Anuncio.find(params[:id])
    @categories = Category.find( :all , :order => 'nome ')
    3.times { @anuncio.assets.build }

  end

  # POST /anuncios
  # POST /anuncios.json
  def create
    @anuncio = Anuncio.new(params[:anuncio])
    @categories = Category.find( :all , :order => 'nome ')

    respond_to do |format|
      if @anuncio.save
        format.html { redirect_to @anuncio, notice: 'Anuncio was successfully created.' }
        format.json { render json: @anuncio, status: :created, location: @anuncio }
      else
        format.html { render action: "new" }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /anuncios/1
  # PUT /anuncios/1.json
  def update
    @anuncio = Anuncio.find(params[:id])

    respond_to do |format|
      if @anuncio.update_attributes(params[:anuncio])
        format.html { redirect_to @anuncio, notice: 'Anuncio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anuncios/1
  # DELETE /anuncios/1.json
  def destroy
    @anuncio = Anuncio.find(params[:id])
    @anuncio.destroy

    respond_to do |format|
      format.html { redirect_to anuncios_url,:notice => "Anuncio apagado com sucesso" }
      format.json { head :no_content }
    end
  end

  def find_anuncios
    
    @categories = Category.find( :all , :order => 'nome ')

    @anuncios = Anuncio.advanced_search(params[:nome],params[:category_id],params[:tipo],params[:minimum_price],params[:maximum_price]).order(sort_column + " " + sort_direction).paginate(:page => params[:page],:per_page => 9)

  end

private
  def sort_column
    #coluna default da pesquisa
    params[:sort] || "nome" 
  end
  
  def sort_direction
    #default ascendente da pesquisa
    params[:direction] || "asc" 
  end




  

end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/views/anuncios/_anuncio.html.erb
<ul class="thumbnails">
             <li class="span3" >
                <div class="thumbnail" >
                    <span><%= anuncio.preco %>€</span>
                     <%= link_to image_tag( 'zenith.jpg'), anuncio , :style => "width: 300px; height: 200px;", :alt => "300x200" %>
                      <div class="caption">
                        <h3><%= anuncio.nome %></h3>
                       <p><%= anuncio.descricao %></p>
                        <p><%= link_to 'Show', anuncio %></p>
                      </div>  
                 </div>
             </li>
    </ul>

app/views/anuncios/_anuncios.html.erb
<% if @anuncios.count == 0 %>
 <div class="span9">
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Warning!</strong> Não foram encontrados anúncios que correspondam a esses critérios
  </div>
</div>
<% else %>

  

  <div class="sort">
    <ul class="nav nav-pills" id="sort11">
      <li  class="<%= 'active' if params[:sort]=="nome" || params[:sort].blank?  %>"><%= sortable "nome", "Nome"%></li>
      <li class="<%= 'active' if params[:sort]=="preco" %>"><%= sortable "preco" , "Preco"%></li>
      <li class="<%= 'active' if params[:sort]=="created_at" %>"><%= sortable "created_at", "Data Criação" %></li>
      <li class="<%= 'active' if params[:sort]=="category_id" %>"><%= sortable "category_id" , "Categoria"%></li>
    </ul>
  </div>

  <% if flash[:notice] %>
          <div class="span9">
              <div class="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:notice] %>
              </div>
          </div>
    <% end %>
    <% if flash[:error] %>
      <p class="error"><%= flash[:error] %></p>
  <% end %>


    <div class="span9">
        <ul class="thumbnails">
            <% @anuncios.each do |anuncio| %>
                 <li class="span3" >
                    <div class="thumbnail" >
                        <span><%= anuncio.preco %>€</span>
                         <%= link_to  image_tag( anuncio.assets.first.image(:small) ) , anuncio , :style => "width: 300px; height: 200px;", :alt => "300x200" %>
                          <div class="caption">
                            
                            <h3><%= anuncio.nome %></h3>
                           <p>

                           <strong> <%=  get_nome_categoria(anuncio.category_id) %></strong> 
                            &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;
                              <% if current_page?(anuncios_path)  %>
                                <%= anuncio.tipo %>
                              <% end %>
                            <p>
                           <p><%= anuncio.descricao %></p>
                            
                           
                            <p><%= link_to 'Show ', anuncio %>&nbsp;&nbsp;&nbsp;&nbsp;
                               <% if isModerador? || belongs_toUser?(anuncio.user_id)%>
                                <%= link_to 'Edit', edit_anuncio_path(anuncio) %>
                            <% end %>
                            </p>
                          </div>  
                     </div>
                 </li>
            <% end %>
            
        </ul>
    </div>
<% end %>

app/views/anuncios/_dashboard2.html.erb
<div class="categories">
 <div class="row">
	 <div class="span9"><!-- start categories -->
		<ul class="thumbnails">
      <%  arry = [
             image_tag('cat_mp3.jpg'),
             image_tag('cat_camera_photo.png'),
             image_tag('informatica.jpg'),
             image_tag('cat_phone.png'),
             image_tag('sony-rolly.jpg'),
             image_tag('cat_games.png'),
             ]
          i = 0;
      %>
      <% @categories.each do |categoria| %>
          <li class="span3">
            <div class="thumbnail">
              <%= link_to  image_tag categoria.cassets.first.image(:small) %>
              <div class="caption">
  			      <a href="listings.html"><h5><%= categoria.nome %></h5></a>
              </div>

            </div>
          </li>
          <% i += 1 %>
       <% end %>
      </ul>
	  </div><!-- end  -->
  </div>
</div><!--end class=categories-->

app/views/anuncios/_destaques.html.erb
  <div class="span7">
    <div>
      <h3>Destaques</h3>
      <div class="row-fluid">
      <div id="featured" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
        <ul class="thumbnails">
        <% i = 0 %>
        <% @destaques1.each do |a| %>

            <li class="span3">
              <div class="thumbnail">
              <i class="tag"></i>
                 <%= link_to  image_tag( a.assets.first.image(:small) ) , a %>
              <div class="caption">
                <%= a.nome %>
                <h4><span class="pull-right"><%= a.preco %></span></h4>
              </div>
              </div>
              <% i +=1 %>
            </li>

        <% end %>
        
        </ul>
        </div>
         <div class="item">
        <ul class="thumbnails">
             <% @destaques2.each do |a| %>
              <%  if a.destaque == true %>
                
                <li class="span3">
                  <div class="thumbnail">
                  <i class="tag"></i>
                     <%= link_to  image_tag( a.assets.first.image(:small) ) , a %>
                  <div class="caption">
                    <%= a.nome %>
                    <h4><span class="pull-right"><%= a.preco %></span></h4>
                  </div>
                  </div>
                </li>

              <% end %>
            <% end %>
          
        </ul>
        </div>
      </div>
        <a class="left carousel-control" href="#featured" data-slide="prev" style="margin-left:-100px;">‹</a>
        <a class="right carousel-control" href="#featured" data-slide="next" style="margin-right:-100px;">›</a>
        </div>
        </div>

app/views/anuncios/compra.html.erb
<%= render :partial => 'left-bar' %>


<div id="anuncios">
	<%= render :partial => 'anuncios' %>
</div>

<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<div class="paginate">
	<%= will_paginate @anuncios, :inner_window => 2 %>
</div>

app/views/anuncios/dashboard.html.erb
<% if  signed_in? && current_user.dashboard == "E"  %>

   <%= render :partial => 'dashboard3' %>
<% else %>

  <%= render :partial => 'left-bar' %>



 
  <div class="categories">
   <div class="row">
  	 <div class="span9"><!-- start categories -->
  		<ul class="ch-grid">
        <%  
            i = 1;
        %>
        <% @categories.each do |categoria| %>
            <li>
              <div class="ch-item ch-img-<%= i %>">
                <div class="ch-info" onclick="location.href='http://localhost:3000/anuncios?category_id=<%= categoria.id %>'" id="<%= categoria.id %>">
                  <h3><%= categoria.nome %></h3>
                </div>

              </div>
            </li>
            <% i += 1 %>
         <% end %>
        </ul>
  	  </div><!-- end  -->
    </div>
  </div><!--end class=categories-->

  <div class="destaques" >
    <%= render 'destaques' %>
 </div>


<% end %>

app/views/anuncios/desactivos.html.erb
<%= render :partial => 'anuncios' %>



<%= will_paginate(@anuncios, :renderer => WillPaginate::ActionView::LinkRenderer) %>

app/views/anuncios/edit.html.erb
<h1>Editing anuncio</h1>

<%= render 'form' %>

<%= link_to 'Show', @anuncio %> |
<%= link_to 'Back', anuncios_path %>

app/views/anuncios/estatisticas.html.erb
<%= high_chart("my_id", @h1) %>


<br>

<% @obj.each do |f| %>
	<%= f %>
<% end %>

app/views/anuncios/find_anuncios.js.erb
$("#anuncios").html("<%= escape_javascript(render :partial => 'anuncios') %>");

app/views/anuncios/index.js.erb
$("#anuncios").html("<%= escape_javascript(render :partial => 'anuncios') %>");

app/views/anuncios/show.html.erb
<div class="info">
  <div class="details">
    <div class="row preco">
         <div class="span9">
          <h1><%= @anuncio.nome %></h1>
         </div>
    </div>
      <br><br>

      <% 
      #numero de imagens do anuncios
      num_img = quantas_imagens_tem?(@anuncio.assets.count) 
      %>
       <div class="row">
         <div class="span4">

           <div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
                    <div class="carousel-inner">
                      <div class="item active"><!-- class of active since it's the first item -->
                        <%= image_tag @anuncio.assets.first.image(:small) %>
                        
                      </div>
                      
                   <% if num_img >= 2 %>
                      <div class="item">
                        <%= image_tag @anuncio.assets[1].image(:small) %>
                      </div>
                  <% end %>

                  <% if num_img == 3 %>
                      <div class="item">
                        <%= image_tag @anuncio.assets[2].image(:small) %>
                        
                  <% end %>
                    </div><!-- /.carousel-inner -->
                   <% if num_img > 1 %>
                    <!--  Next and Previous controls below
                          href values must reference the id for this carousel -->
                      <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
                      <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
                  <% end %>
                  </div><br><!-- /.carousel -->
          
          
                <% if num_img > 1%>
                    <ul class="thumbnails">
                      
                     <% i = 1  %>
                        <% while i < num_img  %>
                            <li class="span2">
                              <a href="#" class="thumbnail"> 
                              <%= image_tag @anuncio.assets[i].image(:small) %>
                              <% i += 1 %>
                              </a>
                            </li>
                        <% end %>
                    </ul>

                  </div> 
              <% end %>

    <!--info anuncio-->
      <div class="info_anuncio">
        <div class="span6">
        
        <div class="span6">
          <address>
            <strong>Descricao: </strong> <span><%= @anuncio.descricao %></span><br><br>
          </address>
        </div>  
            
        <div class="span6">
          
          <div class="preco1">
              <h2>
              <strong>Preço: €<%= @anuncio.preco %></strong> <br /><br />
              </h2>
          </div>

          <p>
           <strong>Criado há <%=  time_ago_in_words(@anuncio.created_at)  %></strong><br /><br />
          </p>

           <p>
             <strong>Tipo: <span class="label label-info"><%= @anuncio.tipo %></span></strong><br /><br />
             
            </p>

         
           <p>
            <strong>Catgoria:<span class="label label-warning"><%= @category_name %></span></strong><br /><br />
            
          </p>
        
         <p>
          <strong>
            Utilizador do anuncio:
            <% u = User.find(@anuncio.user_id) %>
            <%= link_to name = u[:username], u %>
          </strong><br /><br />
        </p> 
    </div><!--fim info anuncio--> 
 
  </div>
    <!--BAckENd ZONE-->
    <div class="backend">
        <% if isModerador? || belongs_toUser?(@anuncio.user_id) %>
          <%= link_to 'Destroy', @anuncio , method: :delete, data: { confirm: 'Are you sure?' } ,:class =>'btn btn-important'%>
          <%= link_to 'Edit', edit_anuncio_path(@anuncio),:class =>'btn' %>

          <%= if isActivo?(@anuncio.activo)  && belongs_toUser?(@anuncio.user_id)
              link_to "Fechar negócio!!", desactivar_anuncio_path , method: :desactivar, data: { confirm: 'Tem a certeza?' } ,:class =>'btn'
             elsif !isActivo?(@anuncio.activo)  && belongs_toUser?(@anuncio.user_id)
               link_to "Re-Activar", activar_anuncio_path , method: :activar, data: { confirm: 'Tem a certeza?' } ,:class =>'btn'
            end
          %>

        <% end %>
        
    </div><!--fim do backend zone--> 

        <div class="mail">

          <p>
            <%= link_to  image_tag('social_icons/facebook.jpg') ,"http://www.facebook.com",:title=>"Partilhar no Facebook" %> 
            <%= link_to  image_tag('social_icons/twitter.jpg') ,"http://www.twitter.com" ,:title=>"Partilhar no Twitter"%>
          <p>
          <br>
          <button class="btn btn-primary" type="submit">Add to WishList</button><br><br>

        </div>

      </div>


      <% if isActivo?(@anuncio.activo) %>
        <div class="row">
        <div class="span9">
        <div class="tabbable">
        <ul class="nav nav-tabs">
        <li class="active"><a href="#1" data-toggle="tab">Descrição</a></li>
        <li><a href="#2" data-toggle="tab">Reviews</a></li>
        <li><a href="#3" data-toggle="tab">Anuncios Relacionados</a></li>
        </ul>
        <div class="tab-content">
        <div class="tab-pane active" id="1">
        <p><%= @anuncio.descricao %></p>
        </div>
        <div class="tab-pane" id="2">
        <p>There are no reviews for this product.</p>
        </div>    



      <div class="tab-pane" id="3">
            <ul class="thumbnails related_products">
            <% if !@anuncios_relacionados.nil? %> 
              <% @anuncios_relacionados.each do |a| %>
                <% if a.id !=  @anuncio.id %>
                 <li class="span2">
                      <div class="thumbnail">
                         <%= link_to (image_tag a.assets.first.image(:small) ), a %>
                        <div class="caption">
                          <a href="product.html"> <h5><%= a.nome %></h5></a>  Preco: €<%= a.preco %><br /><br />
                        </div>
                      </div>
                    </li>
                  <% end %>
              <% end %>
            <% end %>

          


            </ul>
        </div>
        </div>
        </div>

        </div>
        </div>

<% end %>

       
      
        </div>
  </div>
</div>

app/views/anuncios/troca.html.erb
<%= render :partial => 'left-bar' %>

<div id="anuncios">
  <%= render :partial => 'anuncios' %>
</div>

<div class="paginate">
	<%= will_paginate @anuncios, :inner_window => 2 %>
</div>

app/views/anuncios/venda.html.erb
<%= render :partial => 'left-bar' %>

<div id="anuncios">
	<%= render :partial => 'anuncios' %>
</div>


<div class="paginate">
	<%= will_paginate @anuncios, :inner_window => 2 %>
</div>