config/routes.rb
Web::Application.routes.draw do
  
  resources :categories
  
  resources :anuncios

  resources :anuncios, :only => [:show] do
    member do
      post :activar
      post :desactivar
    end
  end
  
  resources :users
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "painel" => "users#painel", :as => "painel"

  get "profile" => "users#show", :as => "profile"
  
  get "venda" => "anuncios#venda", :as => "venda"
  get "compra" => "anuncios#compra", :as => "compra"
  get "troca" => "anuncios#troca", :as => "troca"
  
  get "desactivos" => "anuncios#desactivos", :as => "desactivos"

  get "estatisticas" => "anuncios#estatisticas", :as =>"estatisticas"

  

  root :to => "users#new"

  get "pesq" => "anuncios#find_anuncios", :as => "pesq"
  get "dashboard" => "anuncios#dashboard" ,:as => "dashboard"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Projecto Eng.Web</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Include Stylesheets -->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>



  <%= csrf_meta_tags %>

  </head>

  <body>
    <!-- Start Header/Navbar  -->

    <div  class="navbar navbar-static-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'Olx++', dashboard_path, :class => "brand" %>
          <div class="nav-collapse collapse">
            <ul class="nav">
              
              <li class="<%= 'active' if current_page?(anuncios_path) %>"><%= link_to 'Anúncios', anuncios_path %></li>
              <li class="<%= 'active' if current_page?(venda_path) %>"><%= link_to 'Venda', venda_path %></li>
              <li class="<%= 'active' if current_page?(compra_path) %>"><%= link_to 'Compra', compra_path %></li>
              <li class="<%= 'active' if current_page?(troca_path) %>"><%= link_to 'Troca', troca_path %></li>


              <% if isAdmin? %><!--verifica se é admin-->
              <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to 'Utilizadores', users_path %></li>
              <% end %>

              <li class="<%= 'active' if current_page?(new_anuncio_path) %>"><%= link_to 'Novo Anuncio', new_anuncio_path %></li>
              <% if isModerador?  %>
                 <li class="<%= 'active' if current_page?(categories_path) %>"><%= link_to 'Categorias', categories_path %></li>
              <% end %>
              
              <% if signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to current_user.username+ "´s Profile", profile_path%></li>

                      <% if isAdmin? %>
                        <li ><%= link_to 'Painel', "/painel" %></li>
                      <% end %>
                      <li ><%= link_to 'Desactivos', desactivos_path %></li>

                    <li><a href="#">WishList</a></li>
                    <li class="divider"></li>
                    <li><%= link_to "Log out", log_out_path %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Login", log_in_path %></li>
              <% end %>


            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

                  
    <!-- End Header/Navbar  -->

  <!-- Start Main Content  -->

  <div class="container">

<!-- Start Search Section  -->

    <div id="search-section">
       <div class="row">
        <div class="span12">
          <%= form_tag anuncios_path, :method => 'get'  ,:class => 'form-inline' do  %>
            <%= text_field_tag :nome, params[:nome], :class =>"span5 search-input", :placeholder => "Procura por keyword..." %>
             <%= submit_tag "Search", :nome => nil,:class => 'btn btn-blue'  %>

          <% end %>
        </div>
      </div>
    </div> 

  <!-- End Search Section  -->
  <div id="content">
    <%= yield %>
  </div>
</div>
</div>
  <!-- Start Footer -->

<footer class="footer">
    <div class="container">
    <div class="row">
    <div class="span6"><p><strong>&copy; Olx++</strong> Grupo xxx</p></div>
    <div class="span6">  <ul class="footer-links">
            <li><a href="#">Home</a></li>
            <li class="muted">·</li>
            <li><a href="#">About</a></li>
             <li class="muted">·</li>
            <li><a href="#">Contact</a></li>
            <li class="muted">·</li>
            <li><a href="#">Features</a></li>
            <li class="muted">·</li>
            <br><br>
            <li>    
              <%= link_to  image_tag('social_icons/facebook.jpg') ,"http://www.facebook.com" %> 
              <%= link_to  image_tag('social_icons/twitter.jpg') ,"http://www.twitter.com" %>
              <%= link_to  image_tag('social_icons/you_tube.jpg') ,"http://www.youtube.com" %>   
            </li>
           </ul>
          </div>
           </div>

    </div>


</div> 

  </footer>


 <!-- End Footer -->



    
  </body>
</html>